Data=[
    {
        name:'Pakistan',
        img:'',
        cities:[
       {
        name:'Lahore',
        img:'',
        h1:''
        
       },{
        name:'Islamabad',
        img:'',
       h1:'' 
       },{
        name:'Karachi',
        img:'',
        h1:''
       }
        ],
        h1:'PK'
    },
    {
        name:'India',
        img:'',
        cities:[
            {
                name:'Mumbai',
                img:'',
                h1:''
            },
            {
                name:'Delhi',
                img:'',
                h1:''   
            },{
                name:'Kolkata',
                img:'',
                h1:''
            }
        ],
        h1:'barat'
    },
    {
        name:'China',
        img:'',
        cities:[
            {
                name:'Shanghai',
                img:'',
                h1:""
            },
            {
                name:'Beijing',
                img:'',
                h1:''
            },{
                name:'Guangzhou',
                img:'',
                h1:''
            }
        ],
        h1:''
    },
    {
        name:'America',
        img:'',
        cities:[
            {
            name:'New York',
            img:'',
            h1:''

            },
            {
                name:'Los Angeles',
                img:'',
                h1:''
            },{
                name:'Chicago',
                img:'',
                h1:''
            }
        ]
        
    },
    {
        name:'England',
        img:'',
        cities:[
            {
                name:'London',
                img:'',
                h1:''
            },{
                name:'Manchester',
                img:'',
                h1:''
            },
            {
                name:'Birmingham',
                img:'',
                h1:''
            }
        ]
        
    },
    {
        name:'Japan',
        img:'',
        cities:[
            {
                name:'Tokyo',
                img:'',
                h1:''
            }
        ]
       
    },
]