const Data=[
    {
        name:'Pakistan',
        img:'/images/pk.jpg',
        cities:[
       {
        name:'Lahore',
        img:'/images/pk_1.jpg',
        h1:''
        
       },{
        name:'Islamabad',
        img:'/images/pk_2.jpg',
       h1:'' 
       },{
        name:'Karachi',
        img:'/images/pk_3.jpg',
        h1:''
       }
        ],
        h1:'PK'
    },
    {
        name:'India',
        img:'/images/ind.jpg',
        cities:[
            {
                name:'Mumbai',
                img:'/images/ind_1.jpg',
                h1:''
            },
            {
                name:'Delhi',
                img:'/images/ind_2.jpg',
                h1:''   
            },{
                name:'Kolkata',
                img:'/images/ind_3.jpg',
                h1:''
            }
        ],
        h1:'barat'
    },
    {
        name:'China',
        img:'/images/china.jpg',
        cities:[
            {
                name:'Shanghai',
                img:'/images/china_1.jpg',
                h1:""
            },
            {
                name:'Beijing',
                img:'/images/china_2.jpg',
                h1:''
            },{
                name:'Guangzhou',
                img:'/images/china_3.jpg',
                h1:''
            }
        ],
        h1:''
    },
    {
        name:'America',
        img:'/images/america.jpg',
        cities:[
            {
            name:'New York',
            img:'/images/america.jpg',
            h1:''

            },
            {
                name:'Los Angeles',
                img:'/images/america.jpg',
                h1:''
            },{
                name:'Chicago',
                img:'/images/america.jpg',
                h1:''
            }
        ],
        h1:'america'
        
    },
    {
        name:'England',
        img:'/images/eng.jpg',
        cities:[
            {
                name:'London',
                img:'/images/eng_1.jpg',
                h1:''
            },{
                name:'Manchester',
                img:'/images/eng_2.jpg',
                h1:''
            },
            {
                name:'Birmingham',
                img:'/images/eng_3.jpg',
                h1:''
            }
        ]
        
    },
    {
        name:'Japan',
        img:'/images/japan.jpg',
        cities:[
            {
                name:'Tokyo',
                img:'/images/j_1.jpg',
                h1:''
            },
            {
                name:'Osaka',
                img:'/images/j_2.jpg',
                h1:''
            },
            {
                name:'Kyoto',
                img:'/images/j_3.jpg',
                h1:''
            }
        ],
        h1:'japan'
       
    },
]

export default Data;